import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavLink } from "src/components/NavLink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="box">
          <nav>
            <NavLink href="/">home</NavLink>
            <NavLink href="/useActionStatePage">useActionStatePage</NavLink>
          </nav>
          <article
            className="p-4 bg-gray-100 rounded-md shadow-md"
            style={{ minHeight: "calc(100vh - 4rem)" }}
          >
            {children}
          </article>
        </main>
      </body>
    </html>
  );
}
